### ISSUE TITLE
data_handle_task test randomly hangs with Legion backend

### ISSUE THREAD

**Issue by jlippuner** [laristra/flecsi#489]
The data_handle_task test sometimes hangs with the Legion backend. This happens on my workstation as well as Travis CI (where we allow non-CI tests with Legion to fail), see e.g. https://travis-ci.org/laristra/flecsi/jobs/448122991

**Comment by jpietarilagraham** [comment]
What branch is this?

**Comment by jlippuner** [comment]
master

**Comment by eddy16112** [comment]
I used the following script to run data_handle_task 100 times, but I can not catch the bug. 

set -x
for i in {1..100}
do
    echo "test $i times"
    mpirun -np 2 ./data_handle_task
done

**Comment by ipdemes** [comment]
@jlippuner : I can't reproduce the bug either. Are you running on your vistual machine? What compilers do you use? do you use OpenMPI or mpich? I guess you can try reproducing it in the Docker container (maybe in the one from CI)?

**Comment by jlippuner** [comment]
Thanks for looking into this. It fails about 50% of the time for me. If the test succeeds, it takes about 3 seconds. So if it takes longer than 20 seconds or so, I abort it, assuming that it will hang indefinitely. I'm running this on Debian (not a virtual machine) with GCC 8.2.0 and OpenMPI 3.1.2.
Here is the verbose output. First, when the test succeeds I get this:
```
$ ctest -V -R data_handle_task
UpdateCTestConfiguration  from :/home/jlippuner/progs/flecsi/build_legion/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/jlippuner/progs/flecsi/build_legion/DartConfiguration.tcl
Test project /home/jlippuner/progs/flecsi/build_legion
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 11
    Start 11: data_handle_task

11: Test command: /usr/bin/mpiexec "-n" "2" "/home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task" "--gtest_color=no"
11: Test timeout computed to be: 10000000
11: [0 - 7f66c6da5a00] {4}{threads}: reservation ('EndpointManager workers') cannot be satisfied
11: [1 - 7fadd68bca00] {4}{threads}: reservation ('EndpointManager workers') cannot be satisfied
11: MPI Rank 0 maps to Legion Address Space 0
11: MPI Rank 1 maps to Legion Address Space 1
11: [0 - 7f66c43ea700] {4}{runtime}: [warning 1071] LEGION WARNING: WARNING: Region requirement 0 of operation global_data_handle_dump (UID 66) is using uninitialized data for field(s) 25 of logical region (8,2,2) (from file /home/jlippuner/progs/flecsi-third-party/legion/runtime/legion/region_tree.cc:11167)[warning 1071] 
11: For more information see:
11: http://legion.stanford.edu/messages/warning_code.html#warning_code_1071
11: 
11: This is an mpi task, val = 10
11: This is an mpi task, val = 10
11: This is an mpi task, val = 11
11: This is an mpi task, val = 11
11: This is an mpi task, val = 10
11: This is an mpi task, val = 10
11: [==========] Running 1 test from 1 test case.
11: [----------] Global test environment set-up.
11: [----------] 1 test from data_handle
11: [ RUN      ] data_handle.testname
11: [==========] Running 1 test from 1 test case.
11: [----------] Global test environment set-up.
11: [----------] 1 test from data_handle
11: [ RUN      ] data_handle.testname
11: [       OK ] data_handle.testname (0 ms)
11: [----------] 1 test from data_handle (0 ms total)
11: 
11: [----------] Global test environment tear-down
11: [       OK ] data_handle.testname (0 ms)
11: [----------] 1 test from data_handle (0 ms total)
11: 
11: [----------] Global test environment tear-down
11: [==========] 1 test from 1 test case ran. (0 ms total)
11: [  PASSED  ] 1 test.
11: [==========] 1 test from 1 test case ran. (0 ms total)
11: [  PASSED  ] 1 test.
1/1 Test #11: data_handle_task .................   Passed    3.18 sec

The following tests passed:
        data_handle_task

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   3.19 sec
```
When it fails (about half of the time I try to run it), I get this:
```
$ ctest -V -R data_handle_task
UpdateCTestConfiguration  from :/home/jlippuner/progs/flecsi/build_legion/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/jlippuner/progs/flecsi/build_legion/DartConfiguration.tcl
Test project /home/jlippuner/progs/flecsi/build_legion
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 11
    Start 11: data_handle_task

11: Test command: /usr/bin/mpiexec "-n" "2" "/home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task" "--gtest_color=no"
11: Test timeout computed to be: 10000000
11: [0 - 7f1e21937a00] {4}{threads}: reservation ('EndpointManager workers') cannot be satisfied
11: [1 - 7f8839fa5a00] {4}{threads}: reservation ('EndpointManager workers') cannot be satisfied
11: MPI Rank 0 maps to Legion Address Space 0
11: MPI Rank 1 maps to Legion Address Space 1
11: [0 - 7f1e1af7a700] {4}{runtime}: [warning 1071] LEGION WARNING: WARNING: Region requirement 0 of operation global_data_handle_dump (UID 66) is using uninitialized data for field(s) 25 of logical region (8,2,2) (from file /home/jlippuner/progs/flecsi-third-party/legion/runtime/legion/region_tree.cc:11167)[warning 1071] 
11: For more information see:
11: http://legion.stanford.edu/messages/warning_code.html#warning_code_1071
11: 
11: This is an mpi task, val = 10
11: This is an mpi task, val = 10
11: This is an mpi task, val = 11
11: This is an mpi task, val = 11
11: This is an mpi task, val = 10
11: This is an mpi task, val = 10
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.
[....]
```
And it just keeps going printing out the same warning. I've never left it running for more than a few minutes, so I don't know whether it would eventually complete.
Also note that Legion prints out a warning at the beginning about uninitialized data, but that warning is also present if the test succeeds.

I seem to have linked the wrong CI job in the first comment. That build succeeded, but this one (https://travis-ci.org/laristra/flecsi/jobs/447269937) fails and seems to show the same issue, so the CI sees the random failures too.

**Comment by eddy16112** [comment]
I reproduced the bug with mpi conduit, and it works fine with ibv conduit. I think it is an bug of Open MPI: somehow a reentrancy of a routine is triggered(which is designed to be non-reentrant), and causes deadlocks. 

I also tried to let the Legion mapper to use SERIALIZED_NON_REENTRANT_MAPPER_MODEL, but it does not solve the problem. 

BTW, @ipdemes I found out all tests will get wrong results if MAPPER_COMPACTION=OFF in master branch.

**Comment by eddy16112** [comment]
It is a bug of OpenMPI, and they fixed in their master branch, but not sure it has been fixed in any public release.
https://github.com/open-mpi/ompi/pull/5525

**Comment by ipdemes** [comment]
@eddy16112 : thank you for checking this out!

Yes, it is known issue that MAPPER_COMPACTION=OFF is not working in the master. We decided to not spend time fixing it since we are moving to the Control-replication branch

**Comment by jlippuner** [comment]
> It is a bug of OpenMPI, and they fixed in their master branch, but not sure it has been fixed in any public release.
> [open-mpi/ompi#5525](https://github.com/open-mpi/ompi/pull/5525)

You are right that this OpenMPI fix is not part of any release yet. I just built ompi master to test whether that fix really solves this issue. Unfortunately, it doesn't. This test still hangs randomly and I get the following output
```
UpdateCTestConfiguration  from :/home/jlippuner/progs/flecsi/build_legion/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/jlippuner/progs/flecsi/build_legion/DartConfiguration.tcl
Test project /home/jlippuner/progs/flecsi/build_legion
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 10
    Start 10: data_handle_task

10: Test command: /home/jlippuner/progs/ompi_install/bin/mpiexec "-n" "2" "/home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task" "--gtest_color=no"
10: Test timeout computed to be: 10000000
10: [0 - 7f90ab25c900] {4}{threads}: reservation ('EndpointManager workers') cannot be satisfied
10: [1 - 7fac9396e900] {4}{threads}: reservation ('EndpointManager workers') cannot be satisfied
10: MPI Rank 0 maps to Legion Address Space 0
10: MPI Rank 1 maps to Legion Address Space 1
10: [0 - 7f90a93bd700] {4}{runtime}: [warning 1071] LEGION WARNING: WARNING: Region requirement 0 of operation global_data_handle_dump (UID 66) is using uninitialized data for field(s) 25 of logical region (8,2,2) (from file /home/jlippuner/progs/flecsi-third-party/legion/runtime/legion/region_tree.cc:11167)[warning 1071] 
10: For more information see:
10: http://legion.stanford.edu/messages/warning_code.html#warning_code_1071
10: 
10: This is an mpi task, val = 10
10: This is an mpi task, val = 10
10: This is an mpi task, val = 11
10: This is an mpi task, val = 11
10: This is an mpi task, val = 10
10: This is an mpi task, val = 10
```
Note that the warning `11: [warn] event_base_loop: reentrant invocation.  Only one event_base_loop can run on each event_base at once.` is not displayed anymore. Here's a snapshot from `htop` while the test is hanging:
```
  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
36919 jlippuner  20   0 2336M 67452 55700 S 200.  0.1  9:20.87 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36918 jlippuner  20   0 2338M 68952 56428 R 200.  0.1  9:20.86 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36924 jlippuner  20   0 2336M 67452 55700 R 100.  0.1  4:39.58 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36931 jlippuner  20   0 2336M 67452 55700 R 100.  0.1  4:39.78 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36930 jlippuner  20   0 2338M 68952 56428 R 66.1  0.1  2:53.07 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36925 jlippuner  20   0 2338M 68952 56428 R 62.9  0.1  3:14.24 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36913 jlippuner  20   0  244M 17168 14380 S  0.0  0.0  0:00.07 /home/jlippuner/progs/ompi_install/bin/mpiexec -n 2 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36912 jlippuner  20   0 95564 15080 13364 S  0.0  0.0  0:00.02 ctest -V -R data_handle_task
36914 jlippuner  20   0  244M 17168 14380 S  0.0  0.0  0:00.01 /home/jlippuner/progs/ompi_install/bin/mpiexec -n 2 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36915 jlippuner  20   0  244M 17168 14380 S  0.0  0.0  0:00.00 /home/jlippuner/progs/ompi_install/bin/mpiexec -n 2 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36916 jlippuner  20   0  244M 17168 14380 S  0.0  0.0  0:00.00 /home/jlippuner/progs/ompi_install/bin/mpiexec -n 2 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36917 jlippuner  20   0  244M 17168 14380 S  0.0  0.0  0:00.00 /home/jlippuner/progs/ompi_install/bin/mpiexec -n 2 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36920 jlippuner  20   0 2338M 68952 56428 S  0.0  0.1  0:00.00 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36922 jlippuner  20   0 2338M 68952 56428 S  0.0  0.1  0:00.00 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36926 jlippuner  20   0 2338M 68952 56428 S  0.0  0.1  0:00.01 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36928 jlippuner  20   0 2338M 68952 56428 S  0.0  0.1  0:00.00 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36932 jlippuner  20   0 2338M 68952 56428 S  0.0  0.1  0:00.05 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36934 jlippuner  20   0 2338M 68952 56428 S  0.0  0.1  0:00.15 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36936 jlippuner  20   0 2338M 68952 56428 S  0.0  0.1  0:00.02 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36921 jlippuner  20   0 2336M 67452 55700 S  0.0  0.1  0:00.00 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36923 jlippuner  20   0 2336M 67452 55700 S  0.0  0.1  0:00.00 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36927 jlippuner  20   0 2336M 67452 55700 S  0.0  0.1  0:00.01 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36929 jlippuner  20   0 2336M 67452 55700 S  0.0  0.1  0:00.00 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36933 jlippuner  20   0 2336M 67452 55700 S  0.0  0.1  0:00.07 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36935 jlippuner  20   0 2336M 67452 55700 S  0.0  0.1  0:00.10 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
36937 jlippuner  20   0 2336M 67452 55700 S  0.0  0.1  0:00.01 /home/jlippuner/progs/flecsi/build_legion/test/execution/data_handle_task --gtest_color=no
```

**Comment by cferenba** [comment]
At this very moment, I'm sitting in the OpenMPI meeting at SC.  They have just released version 4.0.0,  and if I'm reading github correctly, 4.0.0 contains this bugfix.

**Comment by jlippuner** [comment]
As far as I can tell from the git history, 4.0.0 does NOT contain the bugfix. Unless it was cherry-picked as a commit with a different hash...

**Comment by jlippuner** [comment]
I take that back. 4.0.0 DOES contain the bugfix, but with a different commit hash, which is why I didn't see it before. I'm going to try the official 4.0.0 release to see if this issue still persists

**Comment by cferenba** [comment]
For the record, it was cherry-picked into the 4.0 series:  open-mpi/ompi#5754

**Comment by jlippuner** [comment]
This test still randomly hangs with OpenMPI 4.0. Additionally, the `simple_task` test randomly segfaults with OpenMPI 4.0.

**Comment by tuxfan** [comment]
@ipdemes will try to reproduce and close issue it she can't...
